### ISSUE TITLE
Use SG API for Mail

### ISSUE THREAD

**Issue by 1UC1F3R616** [Defcon27/Autorizz-Car-Dealership-System-using-NodeJS-Express-MongoDB#1]
To send emails always make use of 3rd party APIs
Try mailgun or SendGrid for this purpose
Don't let ur api key to be commited here
you can add your secrets in config file when working locally and add that in .gitignore for safe handling
use `git status` to check for what's going to be commited on complete add (a common mistake that does happen)

**Comment by Defcon27** [comment]
Yeah, sure will not repeat the mistake next time
