### ISSUE TITLE
Not able to deploy it properly

### ISSUE THREAD

**Issue by Kushal3121** [Defcon27/Autorizz-Car-Dealership-System-using-NodeJS-Express-MongoDB#8]
@Defcon27 When I try to run it on VS Code, the flashcards rather u can say the cars and their details are not visible. Only the navbar with price, range,etc options is being shown. Not able to fix it. Tried my best. Can ya plz help out?
![demo1](https://user-images.githubusercontent.com/58964061/134813407-789f1b31-270d-4959-b3fe-ec2dbe19848e.PNG)

**Comment by Defcon27** [comment]
Hey , did you upload the jsons into mongodb and get it up and running

**Comment by Defcon27** [comment]
@Kushal3121  Hey , did you upload the jsons into mongodb and get it up and running?

**Comment by Defcon27** [comment]
Check General Instruction #3

**Comment by Kushal3121** [comment]
@Defcon27 Yes.. Tried that too.. New at mongodb so facing issues.. Thnx for the help btw..

**Comment by Defcon27** [comment]
so working now ?

**Comment by Kushal3121** [comment]
@Defcon27 Not yet.. Learning how to connect it to mongodb.. Will figure it out soon.. Shall i use Mongodb Compass or its fine on VS Code?

**Comment by Defcon27** [comment]
Compass should be fine. Please do  ⭐ the repo and follow me. 🙃

**Comment by Kushal3121** [comment]
@Defcon27 Connected to mongodb.. It also shows various operations i do like selecting price nd all but still not visible on chrome
![demo11](https://user-images.githubusercontent.com/58964061/135656277-aef840e0-0bda-4c04-89b7-2868d5609e20.PNG)
:(

**Comment by Kushal3121** [comment]
@Defcon27 Shall i add the databse information from db_data to admin in mongodb? And collections should be created with name customer, electricmodel ??? Please help man !!

**Comment by Defcon27** [comment]
Yes, collections name should match exactly and import all the jsons @Kushal3121

**Comment by Kushal3121** [comment]
@Defcon27 Do I need to connect it to a cloud platform ??

**Comment by Defcon27** [comment]
Bruh, are you able to get it up and running in local environment. When deployed on cloud server you do need a cloud database like mongo itself provides free clusters. check it out
